on: 
  push:
    branches: 
      - main
    paths:
      - "selenium-side-runner.Dockerfile"
      - ".github/workflows/docker-build.yml"
  pull_request:
    branches: 
      - main
    paths:
      - "selenium-side-runner.Dockerfile"
      - ".github/workflows/docker-build.yml"

jobs:
  # build and push to ghcr
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./selenium-side-runner.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/selenium-side-runner:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/selenium-side-runner:latest
          cache-to: type=inline
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
            org.opencontainers.image.authors=${{ github.event.repository.owner.login }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.documentation=${{ github.event.repository.html_url }}/blob/main/README.md
            org.opencontainers.image.vendor=${{ github.event.repository.owner.login }}
